fix patch apply

diff --git a/git-xflow b/git-xflow
--- a/git-xflow
+++ b/git-xflow
@@ -52,14 +52,23 @@ require_gitflow_initialized                                 #
 
 ############## General functions ##############
 
-# Displays $1 in brown/orange (overriden from gitflow-common)
+# Displays trace information message $@ in light gray
+trace() { echo -e "${LIGHT_GRAY}$@${NC}"; }
+
+# Displays information message $@ in light blue
+info() { echo -e "${LIGHT_BLUE}$@${NC}"; }
+
+# Displays success message $@ in green
+success() { echo -e "${GREEN}$@${NC}"; }
+
+# Displays warning message $@ in brown/orange (overriden from gitflow-common)
 warn() { echo -e "${BROWN}$@${NC}" >&2; }
 
-# Ends the execution, and displays $1 in bold red (overriden from gitflow-common)
+# Ends the execution, and displays $@ in bold red (overriden from gitflow-common)
 die() { warn "${LIGHT_RED}$@"; exit 1; }
 
-# Ends the execution, and displays a last message ($1 if set, 'Done.' otherwise)
-end() { [ -z "$1" ] && echo -e "${GREEN}Done.${NC}" || echo -e "${GREEN}$1${NC}"; exit 0; }
+# Ends the execution, and displays a last message ($@ if set, 'Done.' otherwise)
+end() { [ -z "$@" ] && echo -e "${GREEN}Done.${NC}" || echo -e "${GREEN}$@${NC}"; exit 0; }
 
 # Ends the execution if given argument $1 is empty and displays usage of subcommand $2, or global usage if $2 is empty
 require_argument() { [ -z "$(eval "echo \$$1")" ] && usage $2 && echo && die "Missing <$1> argument !"; }
@@ -382,10 +391,10 @@ subcommandaction_master_pull() {
 subcommandaction_patch_make() {
     patch_from="$3"; require_argument "patch_from" "patch"
     patch_to="$4"; require_argument "patch_to" "patch"
-    echo "Preparing a patch from '${patch_from}' to '${patch_to}' ..."
+    info "Preparing a patch from '${patch_from}' to '${patch_to}' ..."
     patch_diff=`git diff --name-status ${patch_from}...${patch_to}`
     patch_name="patch_$(basename $(git remote -v | grep fetch | cut -f2 | cut -d\  -f1) | cut -d. -f1)_from_${patch_from}_to_${patch_to}"
-    echo "${patch_diff}"
+    trace "${patch_diff}"
     echo -n "${patch_diff}" > ${patch_name}.log
     assertok "git archive -o ${patch_name}.zip ${patch_to} $(git diff --name-only ${patch_from}...${patch_to})" $LINENO
     end "Successfully built files ${patch_name}.zip|log"
@@ -394,17 +403,16 @@ subcommandaction_patch_make() {
 # Called by: 'git flow patch apply <name>'
 subcommandaction_patch_apply() {
     require_argument "name" "patch"
-    echo "Applying patch $name ..."
-    [ -f "$name.log"] || die "File '$name.log' not found"
-    [ -f "$name.zip"] || die "File '$name.zip' not found"
-    echo -e `less $name.log`
-    echo -n "Copying new files ... "
+    info "Applying patch $name ..."
+    [ -f "$name.log" ] || die "File '$name.log' not found"
+    [ -f "$name.zip" ] || die "File '$name.zip' not found"
+    trace `less $name.log`
+    info "Copying new files ..."
     assertok "unzip $name.zip"
-    echo -n -e "${GREEN}OK${NC}\nRemoving deleted files ..."
+    info "Removing deleted files ..."
     for deleted_file in `less $name.log | grep -v "D\t"`; do 
-        assertok "rm -f $(echo ${deleted_file} | cut -f2)"
+        assertok "rm $(echo ${deleted_file} | cut -f2)"
     done
-    echo -e "${GREEN}OK${NC}"
     end
 }
 
