Fix close

diff --git a/git-xflow b/git-xflow
--- a/git-xflow
+++ b/git-xflow
@@ -22,25 +22,26 @@
 # You should have received a copy of the GNU Lesser General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>
 
-##### Common functions #####
-warn() { echo "$@" >&2; }
-die() { warn "$@"; exit 1; }
-############################
+################ Import gitflow-commom functions ################
+export GITXFLOW_DIR=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
+. "$GITXFLOW_DIR/gitflow-common"
+gitflow_load_settings
+#################################################################
 
 pull()
 {
     case $branch in
         release)
             echo "Pulling release/$target"
-            git checkout release/$target
-            git pull --rebase origin release/$target ;;
+            git checkout release/$target || die "Error !"
+            git pull --rebase $ORIGIN release/$target || die "Error !" ;;
         hotfix)
             echo "Pulling hotfix/$target"
-            git checkout hotfix/$target
-            git pull --rebase origin hotfix/$target ;;
+            git checkout hotfix/$target || die "Error !"
+            git pull --rebase $ORIGIN hotfix/$target || die "Error !" ;;
         *)
             warn "Not supported operation. Using git-flow directly."
-            git flow $branch pull $target ;;
+            git flow $branch pull $target || die "Error !" ;;
     esac
 }
 
@@ -49,44 +50,49 @@ publish()
     case $branch in
         hotfix)
             echo "Publishing hotfix/$target"
-            git checkout release/$target
-            git push origin release/$target ;;
+            git fetch -q $ORIGIN || die "Error !"
+            git push -u $ORIGIN hotfix/$target:hotfix/$target || die "Error !"
+            git fetch -q $ORIGIN hotfix/$target || die "Error !"
+            git checkout hotfix/$target || die "Error !" ;;
         *)
             warn "Not supported operation. Using git-flow directly."
-            git flow $branch publish $target ;;
+            git flow $branch publish $target || die "Error !" ;;
     esac
 }
 
 close()
 {
+    if [ `git_branch_exists "$branch/$target"` ] ; then
+        git flow $branch finish $target || die "Can't finish $branch/$target !'"
+    fi
     case $branch in
         feature)
             echo "Closing feature/$target"
-            git push origin develop
-            git push origin :feature/$target ;;
+            git push $ORIGIN $DEVELOP_BRANCH || die "Error !" ;;
         release)
             echo "Closing release/$target"
-            git push --tags
-            git push origin master
-            git push origin develop
-            git push origin --tags
-            git push origin :release/$target ;;
+            git push --tags || die "Error !"
+            git push $ORIGIN $MASTER_BRANCH || die "Error !"
+            git push $ORIGIN $DEVELOP_BRANCH || die "Error !"
+            git push $ORIGIN --tags || die "Error !" ;;
         hotfix)
             echo "Closing hotfix/$target"
-            git push --tags
-            git push origin master
-            git push origin develop
-            git push origin --tags
-            git push origin :hotfix/$target ;;
+            git push --tags || die "Error !"
+            git push $ORIGIN $MASTER_BRANCH || die "Error !"
+            git push $ORIGIN $DEVELOP_BRANCH || die "Error !"
+            git push $ORIGIN --tags || die "Error !" ;;
         *)
             die "Not supported operation." ;;
     esac
+    if [ `git_local_branch_exists "$branch/$target"` ] ; then
+        git push $ORIGIN :$branch/$target || die "Error !"
+    fi
 }
 
 branch=$1
 action=$2
 target=$3
-if [ -z $branch -o -z $action -o -z $target ] ; then
+if [ -z "$branch" -o -z "$action" -o -z "$target" ] ; then
     echo "git-xflow requires at least 3 arguments : "
     echo "  branch : feature / release / hotfix"
     echo "  action : pull / publish / close"
@@ -105,4 +111,5 @@ case $action in
         die "Not supported operation." ;;
 esac
 
+echo "Done."
 exit 0;
