add assertok

diff --git a/git-xflow b/git-xflow
--- a/git-xflow
+++ b/git-xflow
@@ -43,6 +43,10 @@ require_argument() {
     fi
 }
 
+assertok() {
+    $1 || die "fatal: git-xflow, line $2, following command failed (err: $?): $1"
+}
+
 usage() {
     case "$1" in
         feature)
@@ -106,20 +110,20 @@ action_close() {
     require_argument "$name" "Missing <name> argument !" "$subcommand"
     if git_branch_exists $subcommand/$name; then
         echo "Finishing $subcommand/$name ..."
-        git flow $subcommand finish $name || die "Can't finish $subcommand/$name !"
+        assertok "git flow $subcommand finish $name" $LINENO
     fi
 
     subcommandaction_${subcommand}_${action} "$name" $*
     
     if git_local_branch_exists $subcommand/$name; then
-        git push $ORIGIN :$subcommand/$name || die "$LINENO: Error !"
+        assertok "git push $ORIGIN :$subcommand/$name" $LINENO
     fi
     end
 }
 
 subcommandaction_feature_close() {
     echo "Closing feature/$name ..."
-    git push $ORIGIN $DEVELOP_BRANCH || die "$LINENO: Error !"
+    assertok "git push $ORIGIN $DEVELOP_BRANCH" $LINENO
 }
 
 subcommandaction_staging_merge() {
@@ -129,19 +133,19 @@ subcommandaction_staging_merge() {
     require_local_branch feature/$name
     echo "Merging feature/$name into staging ..."
     if git_remote_branch_exists staging; then
-        git checkout staging || die "$LINENO: Error !"
+        assertok "git checkout staging" $LINENO
     else
         if git_local_branch_exists staging; then
-            git checkout feature/$name
-            git branch -D staging || die "$LINENO: Error !"
+            assertok "git checkout feature/$name" $LINENO
+            assertok "git branch -D staging" $LINENO
         fi
-        git checkout -b staging $DEVELOP_BRANCH || die "$LINENO: Error !"
-        git push --set-upstream $ORIGIN staging || die "$LINENO: Error !"
+        assertok "git checkout -b staging $DEVELOP_BRANCH" $LINENO
+        assertok "git push --set-upstream $ORIGIN staging" $LINENO
     fi
-    git pull || die "$LINENO: Error !"
-    git merge feature/$name || die "$LINENO: Error !"
-    git push || die "$LINENO: Error !"
-    git checkout $previous_branch || die "$LINENO: Error !"
+    assertok "git pull" $LINENO
+    assertok "git merge feature/$name" $LINENO
+    assertok "git push" $LINENO
+    assertok "git checkout $previous_branch" $LINENO
     end
 }
 
@@ -150,57 +154,57 @@ subcommandaction_staging_reset() {
     require_clean_working_tree
     if [ -z "$name" ] ; then
         echo "Resetting staging to $DEVELOP_BRANCH ..."
-        git checkout -B staging $DEVELOP_BRANCH || die "$LINENO: Error !"
+        assertok "git checkout -B staging $DEVELOP_BRANCH" $LINENO
     else
         echo "Resetting staging to feature/$name ..."
         require_local_branch feature/$name
-        git checkout -B staging feature/$name || die "$LINENO: Error !"
+        assertok "git checkout -B staging feature/$name" $LINENO
     fi
-    git push -f --set-upstream $ORIGIN staging || die "$LINENO: Error !"
-    git checkout $previous_branch || die "$LINENO: Error !"
+    assertok "git push -f --set-upstream $ORIGIN staging" $LINENO
+    assertok "git checkout $previous_branch" $LINENO
     end
 }
 
 subcommandaction_release_pull() {
     require_argument "$name" "Missing <name> argument !" "$subcommand"
     echo "Pulling release/$name ..."
-    git checkout release/$name || die "$LINENO: Error !"
-    git pull --rebase $ORIGIN release/$name || die "$LINENO: Error !"
+    assertok "git checkout release/$name" $LINENO
+    assertok "git pull --rebase $ORIGIN release/$name" $LINENO
     end
 }
 
 subcommandaction_release_close() {
     echo "Closing release/$name ..."
-    git push --tags || die "$LINENO: Error !"
-    git push $ORIGIN $MASTER_BRANCH || die "$LINENO: Error !"
-    git push $ORIGIN $DEVELOP_BRANCH || die "$LINENO: Error !"
-    git push $ORIGIN --tags || die "$LINENO: Error !"
+    assertok "git push --tags" $LINENO
+    assertok "git push $ORIGIN $MASTER_BRANCH" $LINENO
+    assertok "git push $ORIGIN $DEVELOP_BRANCH" $LINENO
+    assertok "git push $ORIGIN --tags" $LINENO
 }
 
 subcommandaction_hotfix_publish() {
     require_argument "$name" "Missing <name> argument !" "$subcommand"
     echo "Publishing hotfix/$name to $ORIGIN ..."
-    git fetch -q $ORIGIN || die "$LINENO: Error !"
-    git push -u $ORIGIN hotfix/$name:hotfix/$name || die "$LINENO: Error !"
-    git fetch -q $ORIGIN hotfix/$name || die "$LINENO: Error !"
-    git checkout hotfix/$name || die "$LINENO: Error !"
+    assertok "git fetch -q $ORIGIN" $LINENO
+    assertok "git push -u $ORIGIN hotfix/$name:hotfix/$name" $LINENO
+    assertok "git fetch -q $ORIGIN hotfix/$name" $LINENO
+    assertok "git checkout hotfix/$name" $LINENO
     end
 }
 
 subcommandaction_hotfix_pull() {
     require_argument "$name" "Missing <name> argument !" "$subcommand"
     echo "Pulling hotfix/$name ..."
-    git checkout hotfix/$name || die "$LINENO: Error !"
-    git pull --rebase $ORIGIN hotfix/$name || die "$LINENO: Error !"
+    assertok "git checkout hotfix/$name" $LINENO
+    assertok "git pull --rebase $ORIGIN hotfix/$name" $LINENO
     end
 }
 
 subcommandaction_hotfix_close() {
     echo "Closing hotfix/$name ..."
-    git push --tags || die "$LINENO: Error !"
-    git push $ORIGIN $MASTER_BRANCH || die "$LINENO: Error !"
-    git push $ORIGIN $DEVELOP_BRANCH || die "$LINENO: Error !"
-    git push $ORIGIN --tags || die "$LINENO: Error !"
+    assertok "git push --tags" $LINENO
+    assertok "git push $ORIGIN $MASTER_BRANCH" $LINENO
+    assertok "git push $ORIGIN $DEVELOP_BRANCH" $LINENO
+    assertok "git push $ORIGIN --tags" $LINENO
 }
 
 
@@ -225,5 +229,5 @@ if [ "$disable_gitflow_proxy" = "yes" ] ; then
 else
     warn "Operation not supported by git-xflow, trying with vanilla git-flow ..."
     echo "git flow $*"
-    git flow $*
+    assertok "git flow $*" $LINENO
 fi
