Refactoring, adding config

diff --git a/git-xflow b/git-xflow
--- a/git-xflow
+++ b/git-xflow
@@ -20,7 +20,7 @@
 # GNU Lesser General Public License for more details.
 # 
 # You should have received a copy of the GNU Lesser General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>
+# along with this program. If not, see <http://www.gnu.org/licenses/>
 
 
 
@@ -28,53 +28,19 @@
 
 GITXFLOW_VERSION="0.9.0+160910.2345"
 
-# Colors
-NC='\033[0m'
-BLACK='\033[0;30m';         DARK_GRAY='\033[1;30m'
-RED='\033[0;31m';           LIGHT_RED='\033[1;31m'
-GREEN='\033[0;32m';         LIGHT_GREEN='\033[1;32m'
-BROWN='\033[0;33m';         YELLOW='\033[1;33m'
-BLUE='\033[0;34m';          LIGHT_BLUE='\033[1;34m'
-PURPLE='\033[0;35m';        LIGHT_PURPLE='\033[1;35m'
-CYAN='\033[0;36m';          LIGHT_CYAN='\033[1;36m'
-LIGHT_GRAY='\033[0;37m';    WHITE='\033[1;37m'
 
 
-
-############## Import gitflow-common functions ##############
+############## Import functions and parameters ##############
 GITXFLOW_DIR=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")  #
 . "$GITXFLOW_DIR/gitflow-common"                            #
 gitflow_load_settings                                       #
 require_gitflow_initialized                                 #
+. "$GITXFLOW_DIR/gitxflow-common"                           #
 #############################################################
 
 
 
 ############## General functions ##############
-
-# Displays trace information message $@ in dark gray
-trace() { echo -e "${DARK_GRAY}$@${NC}"; }
-
-# Displays information message $@ in light blue
-info() { echo -e "${LIGHT_BLUE}$@${NC}"; }
-
-# Displays success message $@ in green
-success() { echo -e "${GREEN}$@${NC}"; }
-
-# Displays warning message $@ in brown/orange (overriden from gitflow-common)
-warn() { echo -e "${BROWN}$@${NC}" >&2; }
-
-# Ends the execution, and displays $@ in bold red (overriden from gitflow-common)
-die() { warn "${LIGHT_RED}$@"; exit 1; }
-
-# Ends the execution, and displays a last message ($@ if set, 'Done.' otherwise)
-end() { [ -z "$@" ] && echo -e "${GREEN}Done.${NC}" || echo -e "${GREEN}$@${NC}"; exit 0; }
-
-# Ends the execution if given argument $1 is empty and displays usage of subcommand $2, or global usage if $2 is empty
-require_argument() { [ -z "$(eval "echo \$$1")" ] && usage $2 && echo && die "Missing <$1> argument !"; }
-
-# Ends the execution if given command $1 returns an error and displays debug information. Usage: assertok "command" $LINENO
-assertok() { ! $1 && warn "${LIGHT_RED}fatal: git-xflow v$GITXFLOW_VERSION, line $2, following command failed (err: $?):" && die "$1"; }
 
 # Displays usage information of subcommand $1 if set, or global usage information otherwise
 usage() {
@@ -334,7 +300,7 @@ action_reviewhtml() {
             </div>
         </body>
     </html>"
-    echo "${html_diff}" > "review_${repo_name}_from_${compare_to_branch}_to_${branch_name}.html"
+    echo -n "${html_diff}" > "review_${repo_name}_from_${compare_to_branch}_to_${branch_name}.html"
     end "Review successfully saved into file 'review_${repo_name}_from_${compare_to_branch}_to_${branch_name}.html'."
 }
 
@@ -552,7 +518,7 @@ subcommandaction_version_update() {
     update_version=`echo -n "${update_content}" | grep "^GITXFLOW_VERSION=\"" | awk -F'"' '{print $2}'`
     [ -z "${update_version}" ] && die "Failed to retrieve git-xflow file from remote server"
     echo -n "v${update_version} ... "
-    echo "${update_content}" > "$GITXFLOW_DIR/git-xflow" && end "Success" || die "Failed to replace git-xflow file"
+    echo -n "${update_content}" > "$GITXFLOW_DIR/git-xflow" && end "Success" || die "Failed to replace git-xflow file"
 }
 
 
