Coding conventions from Google

diff --git a/gitxflow-common b/gitxflow-common
--- a/gitxflow-common
+++ b/gitxflow-common
@@ -30,15 +30,17 @@
 
 # Colors
 NC=$'\033[0m'
-BLACK=$'\033[0;30m';         DARK_GRAY=$'\033[1;30m'
-RED=$'\033[0;31m';           LIGHT_RED=$'\033[1;31m'
-GREEN=$'\033[0;32m';         LIGHT_GREEN=$'\033[1;32m'
-BROWN=$'\033[0;33m';         YELLOW=$'\033[1;33m'
-BLUE=$'\033[0;34m';          LIGHT_BLUE=$'\033[1;34m'
-PURPLE=$'\033[0;35m';        LIGHT_PURPLE=$'\033[1;35m'
-CYAN=$'\033[0;36m';          LIGHT_CYAN=$'\033[1;36m'
-LIGHT_GRAY=$'\033[0;37m';    WHITE=$'\033[1;37m'
+BLACK=$'\033[0;30m';        DARK_GRAY=$'\033[1;30m'
+RED=$'\033[0;31m';          LIGHT_RED=$'\033[1;31m'
+GREEN=$'\033[0;32m';        LIGHT_GREEN=$'\033[1;32m'
+BROWN=$'\033[0;33m';        YELLOW=$'\033[1;33m'
+BLUE=$'\033[0;34m';         LIGHT_BLUE=$'\033[1;34m'
+PURPLE=$'\033[0;35m';       LIGHT_PURPLE=$'\033[1;35m'
+CYAN=$'\033[0;36m';         LIGHT_CYAN=$'\033[1;36m'
+LIGHT_GRAY=$'\033[0;37m';   WHITE=$'\033[1;37m'
 
+# Fixes for old version of 'sed' (Mac OS X ...)
+TAB=$'\t';                  LF=$'\n' 
 
 
 ############## General functions ##############
@@ -59,13 +61,13 @@ warn() { echo -e "${BROWN}$@${NC}" >&2; }
 die() { warn "${LIGHT_RED}$@"; exit 1; }
 
 # Ends the execution, and displays a last message ($@ if set, 'Done.' otherwise)
-end() { [ -z "$@" ] && echo -e "${GREEN}Done.${NC}" || echo -e "${GREEN}$@${NC}"; exit 0; }
+end() { [[ -z "$@" ]] && echo -e "${GREEN}Done.${NC}" || echo -e "${GREEN}$@${NC}"; exit 0; }
 
 # Displays question message $@ in light purple
 question() { echo -en "${LIGHT_PURPLE}$@${NC}"; }
 
 # Ends the execution if given argument $1 is empty and displays usage of subcommand $2, or global usage if $2 is empty
-require_argument() { [ -z "$(eval "echo \$$1")" ] && usage $2 && echo && die "Missing <$1> argument !"; }
+require_argument() { [[ -z "$(eval "echo \$$1")" ]] && usage $2 && echo && die "Missing <$1> argument !"; }
 
 # Ends the execution if given command $1 returns an error and displays debug information. Usage: 'assertok "command" $LINENO'
 assertok() { ! $1 && warn "${LIGHT_RED}fatal: git-xflow v$GITXFLOW_VERSION, line $2, following command failed (err: $?):" && die "$1"; }
@@ -82,9 +84,9 @@ gitxflow_load_settings() {
 }
 
 gitxflow_is_initialized() {
-    [ "${STAGING_BRANCH}" != "" ] \
-    && [ "${GITXFLOW_TEMPLATE_REVIEW}" != "" ] \
-    && [ "${GITXFLOW_TEMPLATE_PATCH}" != "" ]
+    [[ "${STAGING_BRANCH}" != "" ]] \
+    && [[ "${GITXFLOW_TEMPLATE_REVIEW}" != "" ]] \
+    && [[ "${GITXFLOW_TEMPLATE_PATCH}" != "" ]]
 }
 
 # Save default settings that can be overridden using git config
@@ -103,69 +105,69 @@ gitxflow_save_default_settings() {
 
 # Parse and evaluate a given template. Usage: 'parse_template <template_name> <generated_file_name> <generated_file_suffix>'
 parse_template() {
-    [ -z "$1" ] && die "Missing template name."
-    [ -z "$2" ] && die "Missing default generated file name."
+    [[ -z "$1" ]] && die "Missing template name."
+    [[ -z "$2" ]] && die "Missing default generated file name."
     local template_name generated_file_name generated_file_suffix template_file lhs value rhs parsed_template
     template_name="$1"
     generated_file_name="$2"
     generated_file_suffix="$3"
     template_file="${GITXFLOW_DIR}/${template_name}"
-    if [ -f "${template_name}" ] ; then
+    if [[ -f "${template_name}" ]]; then
         template_file="${template_name}"
-    elif [ -f "${DOT_GIT_DIR}/${template_name}" ] ; then
+    elif [[ -f "${DOT_GIT_DIR}/${template_name}" ]]; then
         template_file="${DOT_GIT_DIR}/${template_name}"
-    elif [ -f "${DOT_GIT_DIR}/../${template_name}" ] ; then
+    elif [[ -f "${DOT_GIT_DIR}/../${template_name}" ]]; then
         template_file="${DOT_GIT_DIR}/../${template_name}"
     fi
-    if [ ! -f "${template_file}" ] ; then
+    if [[ ! -f "${template_file}" ]]; then
         warn "Template '$1': file not found."
         return 1;
     fi
     parsed_template="$(<${template_file})"
     # Handle variable tags: '<%= variablename %>'
-    while [[ "$parsed_template" =~ (<%=[[:blank:]]*[[:cntrl:]]*[[:blank:]]*([^%[:blank:][:cntrl:]]*).*%>) ]] ; do
+    while [[ "$parsed_template" =~ (<%=[[:blank:]]*[[:cntrl:]]*[[:blank:]]*([^%[:blank:][:cntrl:]]*).*%>) ]]; do
         lhs="${BASH_REMATCH[1]}"
         value="${BASH_REMATCH[2]}"
         rhs="$(eval echo -n "\"\${$value}\"")"
-        if [ $? != 0 ] ; then
+        if [[ $? != 0 ]]; then
             warn "Template '$1': error when evaluating variable tag: '$lhs'."
             return 10;
         fi
         parsed_template="${parsed_template//"$lhs"/"$rhs"}"
     done
     # Handle not echoed command tags: '<%@ command %>'
-    while [[ "$parsed_template" =~ (<%@([^%]*)%>) ]] ; do
+    while [[ "$parsed_template" =~ (<%@([^%]*)%>) ]]; do
         lhs="${BASH_REMATCH[1]}"
         value="${BASH_REMATCH[2]}"
         eval "$value"
-        if [ $? != 0 ] ; then
+        if [[ $? != 0 ]]; then
             warn "Template '$1': error when evaluating not echoed command tag: '$lhs'."
             return 11;
         fi
         parsed_template="${parsed_template//"$lhs"/}"
     done
     # Handle comment tags: '<%# comment #%>'
-    while [[ "$parsed_template" =~ (<%#([^#]*)#%>) ]] ; do
+    while [[ "$parsed_template" =~ (<%#([^#]*)#%>) ]]; do
         lhs="${BASH_REMATCH[1]}"
         parsed_template="${parsed_template//"$lhs"/}"
     done
     # Handle echoed command tags: '<%$ command %>'
-    while [[ "$parsed_template" =~ (<%\$([^%]*)%>) ]] ; do
+    while [[ "$parsed_template" =~ (<%\$([^%]*)%>) ]]; do
         lhs="${BASH_REMATCH[1]}"
         value="${BASH_REMATCH[2]}"
         rhs="$(eval "$value")"
-        if [ $? != 0 ] ; then
+        if [[ $? != 0 ]]; then
             warn "Template '$1': error when evaluating echoed command tag: '$lhs'."
             return 12;
         fi
         parsed_template="${parsed_template//"$lhs"/"$rhs"}"
     done
     # Handle to-file command tags: '<%: command %>'
-    while [[ "$parsed_template" =~ (<%:([^%]*)%>) ]] ; do
+    while [[ "$parsed_template" =~ (<%:([^%]*)%>) ]]; do
         lhs="${BASH_REMATCH[1]}"
         value="${BASH_REMATCH[2]}"
         eval "$value" > "${generated_file_name}${generated_file_suffix}"
-        if [ $? = 0 ] ; then
+        if [[ $? = 0 ]]; then
             info "Template '$1': File '${generated_file_name}${generated_file_suffix}' generated."
             return 0;
         else
@@ -173,7 +175,7 @@ parse_template() {
             return 13;
         fi
     done
-    if [ ! -z "${generated_file_name}${generated_file_suffix}" ] ; then
+    if [[ ! -z "${generated_file_name}${generated_file_suffix}" ]]; then
         echo -n "${parsed_template}" > "${generated_file_name}${generated_file_suffix}"
         info "Template '$1': File '${generated_file_name}${generated_file_suffix}' generated."
     else
