option functions

diff --git a/gitxflow-common b/gitxflow-common
--- a/gitxflow-common
+++ b/gitxflow-common
@@ -72,6 +72,30 @@ require_argument() { [[ -z "$(eval "echo \$$1")" ]] && usage $2 && echo && die "
 # Ends the execution if given command $1 returns an error and displays debug information. Usage: 'assertok "command" $LINENO'
 assertok() { ! $1 && warn "${LIGHT_RED}fatal: git-xflow v${GITXFLOW_VERSION}, line $2, following command failed (err: $?):" && die "$1"; }
 
+has_option() {
+    [[ -z "$1" ]] && die "Missing option name."
+    local option found
+    [[ "$1" =~ ^[[:alnum:]]$ ]] && option="$1" || option='-'
+    while getopts "${option}" found ${GITXFLOW_ARGS}; do
+        [[ "${found}" = "$1" || "${found}" = '-' && "${OPTARG}" = "$1" ]] && return 0;
+    done
+    return 1;
+}
+
+require_option() {
+    ! has_option "$1" && usage $2 && echo && die "Missing <$1> option !";
+}
+
+get_option() {
+    [[ -z "$1" ]] && die "Missing option name."
+    [[ "$1" =~ ^[[:alnum:]]$ ]] || die "Invalid option name: '$1'."
+    local found
+    while getopts "$1:" found ${GITXFLOW_ARGS}; do
+        [[ "${found}" = "$1" ]] && echo "${OPTARG}"; return 0;
+    done
+    return 1;
+}
+
 # Loads settings that can be overridden using git config
 gitxflow_load_settings() {
     readonly REPOSITORY_NAME="$(basename $(git remote -v | grep fetch | cut -f2 | cut -d\  -f1) | cut -d. -f1)"
