templating system

diff --git a/gitxflow-common b/gitxflow-common
--- a/gitxflow-common
+++ b/gitxflow-common
@@ -64,7 +64,7 @@ end() { [ -z "$@" ] && echo -e "${GREEN}Done.${NC}" || echo -e "${GREEN}$@${NC}"
 # Ends the execution if given argument $1 is empty and displays usage of subcommand $2, or global usage if $2 is empty
 require_argument() { [ -z "$(eval "echo \$$1")" ] && usage $2 && echo && die "Missing <$1> argument !"; }
 
-# Ends the execution if given command $1 returns an error and displays debug information. Usage: assertok "command" $LINENO
+# Ends the execution if given command $1 returns an error and displays debug information. Usage: 'assertok "command" $LINENO'
 assertok() { ! $1 && warn "${LIGHT_RED}fatal: git-xflow v$GITXFLOW_VERSION, line $2, following command failed (err: $?):" && die "$1"; }
 
 # Loads settings that can be overridden using git config
@@ -76,6 +76,44 @@ gitxflow_load_settings() {
 
 # Save settings that can be overridden using git config
 gitxflow_save_settings() {
-    assertok "git config gitxflow.template.reviewhtml template-review.html"
-    assertok "git config gitxflow.template.patchmake template-patchmake.sh;template-patchmake.cmd"
+    assertok "git config gitxflow.template.reviewhtml template-reviewhtml"
+    assertok "git config gitxflow.template.patchmake template-patchmake-sh template-patchmake-cmd"
+}
+
+# Parse and evaluate a given template. Usage: 'parse_template <filename>'
+parse_template() {
+    [ -z "$1" ] && die "Missing template name."
+    local template_name template_file line lhs value command rhs
+    template_name="$1"
+    template_file="${GITXFLOW_DIR}/${template_name}"
+    if [ -f "${template_name}" ] ; then
+        template_file="${template_name}"
+    elif [ -f "${DOT_GIT_DIR}/${template_name}" ] ; then
+        template_file="${DOT_GIT_DIR}/${template_name}"
+    elif [ -f "${DOT_GIT_DIR}/../${template_name}" ] ; then
+        template_file="${DOT_GIT_DIR}/../${template_name}"
+    fi
+    [ -f "${template_file}" ] || die "Cannot find template file '${template_file}'."
+    template_content=""
+    while read -r line ; do
+        while [[ "$line" =~ (<%=[[:blank:]]*([^%[:blank:]]*)[[:blank:]]*%>) ]] ; do
+            lhs=${BASH_REMATCH[1]}
+            value=${BASH_REMATCH[2]}
+            rhs="$(eval echo -n "\"\$$value\"")"
+            line=${line//$lhs/$rhs}
+        done
+        while [[ "$line" =~ (<%\$([^%]*)%>) ]] ; do
+            lhs=${BASH_REMATCH[1]}
+            command=${BASH_REMATCH[2]}
+            eval "export $command"
+            line=${line//$lhs/}
+        done
+        while [[ "$line" =~ (<%([^%]*)%>) ]] ; do
+            lhs=${BASH_REMATCH[1]}
+            command=${BASH_REMATCH[2]}
+            rhs="$(eval "$command")"
+            line=${line//$lhs/$rhs}
+        done
+        template_content="${template_content}\n${line}"
+    done < ${template_file}
 }
